### PR TITLE
General website updates

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by rnagpal02 — COMMENTED** [review]
We probably shouldn't delete that whole section. If we still have access to the PDF and power point we should probably add it back in and if not just remove the last sentence with the links.

**Comment by ghost** [comment]
As far as I know the PDF was uploaded directly to Github and no longer exists virtually.

**Comment by rnagpal02** [comment]
That's fine. I would still say only delete the last sentence and keep the rest but if you feel it's not worth it I'll go ahead and merge to the master branch.

**Comment by ghost** [comment]
Just merge. I don't think we should include that if we don't have the
associated documentation.

**Pull request merged**
